name: Hourly Data Snapshot

on:
  schedule:
    - cron: '0 0,8,16 * * *' # Runs at 00:00, 08:00, 16:00 UTC (every 8hrs)

  # Allows you to run it manually from the Actions tab for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Snapshot Script
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        TIME_DELAY: ${{ secrets.TIME_DELAY }}
        TIMEOUT: ${{ secrets.TIMEOUT }}

        WAR: ${{ secrets.WAR }}
        MAJOR_ORDER: ${{ secrets.MAJOR_ORDER }}
        CAMPAIGNS: ${{ secrets.CAMPAIGNS }}
        NEWS_FEED: ${{ secrets.NEWS_FEED }}
        PLANETS: ${{ secrets.PLANETS }}
        PLANET_EVENTS: ${{ secrets.PLANET_EVENTS }}
        STEAM_NEWS: ${{ secrets.STEAM_NEWS }}
        SPACE_STATIONS: ${{ secrets.SPACE_STATIONS }}
        
        USER_AGENT: ${{ secrets.USER_AGENT }}
        SUPER_CLIENT: ${{ secrets.SUPER_CLIENT }}
        SUPER_CONTACT: ${{ secrets.SUPER_CONTACT }}

        SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}

      run: python snapshot.py

    - name: Build Static API Files
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        TIME_DELAY: ${{ secrets.TIME_DELAY }}
        TIMEOUT: ${{ secrets.TIMEOUT }}

        WAR: ${{ secrets.WAR }}
        MAJOR_ORDER: ${{ secrets.MAJOR_ORDER }}
        CAMPAIGNS: ${{ secrets.CAMPAIGNS }}
        NEWS_FEED: ${{ secrets.NEWS_FEED }}
        PLANETS: ${{ secrets.PLANETS }}
        PLANET_EVENTS: ${{ secrets.PLANET_EVENTS }}
        STEAM_NEWS: ${{ secrets.STEAM_NEWS }}
        SPACE_STATIONS: ${{ secrets.SPACE_STATIONS }}

        USER_AGENT: ${{ secrets.USER_AGENT }}
        SUPER_CLIENT: ${{ secrets.SUPER_CLIENT }}
        SUPER_CONTACT: ${{ secrets.SUPER_CONTACT }}

        SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}

      run: python build_static_api.py

    - name: Commit and Push Data
      run: |
        git config user.name "HelldiversDataBot"
        git config user.email "bot@users.noreply.github.com"
        git add data_history/ static-api/
        # Only commit if there are changes (avoids errors if API is down)
        timestamp=$(date -u)
        git commit -m "Data Snapshot: ${timestamp} [skip ci]" || exit 0
        git push